name: Test And Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.101
      - name: Install codecov
        run: dotnet tool install -g codecov.tool
      - name: Run Tests
        working-directory: csharp
        run: dotnet test --settings coverletArgs.runsettings
      - name: Stage code coverage
        working-directory: csharp
        run: mv UnitTests/TestResults/*/coverage.opencover.xml .
      - name: Install 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.607
      - name: Upload coverage
        working-directory: csharp
        run: ~/.dotnet/tools/codecov -f coverage.opencover.xml -t $CODECOV